Arithmetic Operations on Multiple Arrays

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])


In [3]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [5]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [6]:
arr3 = np.array([[1,2],[5,6]])

In [8]:
#arr1 + arr3      #Not possible for different orientations of array
#add sub mul nothing possible if size and orientation is different of array

In [9]:
arr1 * arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [12]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [13]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [14]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [15]:
arr[:2]

array([1, 2])

In [16]:
arr[:-2]

array([1, 2, 3])

In [17]:
arr[2:]

array([3, 4, 5])

In [18]:
arr[-2:]

array([4, 5])

In [19]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr1[ 1:2 , 1:2 ]

array([[5]])

In [29]:
arr1[ 1: , 1: ]

array([[5, 6],
       [8, 9]])