Arithmetic Operations on Array

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr + 1

array([2, 3, 4, 5, 6, 7])

In [6]:
arr *2

array([ 2,  4,  6,  8, 10, 12])

In [7]:
print(arr + 1)
print(arr - 1)
print(arr * 2)
print(arr / 2)
print(arr % 1)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]
[0 0 0 0 0 0]


In [8]:
print(arr ** 2)

[ 1  4  9 16 25 36]


In [9]:
print(arr**3)

[  1   8  27  64 125 216]


In [10]:
arr = arr +1

In [11]:
arr

array([2, 3, 4, 5, 6, 7])

In [12]:
arr *= 2

In [13]:
arr

array([ 4,  6,  8, 10, 12, 14])

In [14]:
arr.max()

14

In [15]:
arr.min()

4

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.max(axis = 0)   #Max element column-wise

array([7, 8, 9])

In [19]:
arr.max(axis = 1)   #Max element row-wise

array([3, 6, 9])

In [20]:
arr.min(axis = 0)

array([1, 2, 3])

In [21]:
arr.min(axis = 1)

array([1, 4, 7])

In [22]:
arr.sum()

45