Arrays Slicing - DAP

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8])

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr[0]

1

In [7]:
arr[5]

6

In [8]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
arr[3:]

array([4, 5, 6, 7, 8])

In [10]:
arr[:-3]

array([1, 2, 3, 4, 5])

In [11]:
arr[3:-3]

array([4, 5])

In [12]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [14]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [15]:
arr1[1,1]

6

In [20]:
arr1[1:3 , 1:3]

array([[6, 7],
       [7, 6]])

In [26]:
arr1[:4 , :4 ]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])