Automating Using NUMPY

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [3]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
q = 0
for i in lst:
    if(i>5):
        q+=1
print(q)

5


In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [9]:
len(arr[arr>5])

5

In [10]:
print(len(arr[arr % 3==0]))
print(arr[arr % 3 == 0])

3
[3 6 9]


In [13]:
arr.dtype

dtype('int32')

In [14]:
c= np.array([6,7,5,8])
d= np.array([4,3,7,8])
pro = c.dot(d)
print(pro)

144


In [16]:
np.flipud(arr)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
np.sort(arr)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [19]:
ques = [1,2,3,5,4,6,7,8,5,3,2]

In [20]:
print(ques[2:-3])

[3, 5, 4, 6, 7, 8]
