Mean

In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,5,7,9])

In [3]:
arr

array([1, 3, 5, 7, 9])

In [5]:
mean = sum(arr)/len(arr)
print(mean)

5.0


In [6]:
np.mean(arr)

5.0

In [7]:
arr = np.array([1,3,5,7,9])
w = np.array([1,2,3,4,5])
np.average(arr,weights = w)

6.333333333333333

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
np.mean(arr1)

3.5

In [11]:
arr1 = np.array([[1,2,3],[4,5,6]])
np.mean(arr1,axis=0)


array([2.5, 3.5, 4.5])

In [12]:
np.mean(arr1,axis=1)

array([2., 5.])

Median

In [13]:
arr = [1,2,3,4,5]
np.median(arr)

3.0

In [14]:
arr = [2,3,4,5]
np.median(arr)

3.5

Mode

In [ ]:
#Numpy does not have a mode function directly

In [19]:
arr3 = [1,2,3,4,4,3,3,5,1]
from collections import Counter
count = Counter(arr3)

In [20]:
count

Counter({1: 2, 2: 1, 3: 3, 4: 2, 5: 1})

In [23]:
count.most_common(1)

[(3, 3)]