Reshape and Random No. Generator


In [1]:
import numpy as np

In [2]:
np.random.random((3,3))

array([[0.58776167, 0.80372641, 0.29495864],
       [0.10363538, 0.59144105, 0.70402944],
       [0.96420971, 0.8189981 , 0.5315108 ]])

In [3]:
np.random.random((3,3))

array([[0.20081713, 0.49034708, 0.70593535],
       [0.55195582, 0.20557804, 0.80613927],
       [0.66810214, 0.11478015, 0.38533834]])

In [6]:
if np.random.random() < 0.5:
    print("Run the function")
else:
    print("Dont run")

Run the function


In [5]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(1,11,10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [8]:
np.linspace(1,11,9)

array([ 1.  ,  2.25,  3.5 ,  4.75,  6.  ,  7.25,  8.5 ,  9.75, 11.  ])

In [9]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
arr = np.random.random((4,3))
arr

array([[0.65407132, 0.34268835, 0.18080346],
       [0.08152986, 0.99132153, 0.21343236],
       [0.12470677, 0.19283782, 0.67332681],
       [0.5671647 , 0.13419959, 0.0134772 ]])

In [13]:
arr = np.reshape(arr, (3,4))


In [14]:
arr

array([[0.65407132, 0.34268835, 0.18080346, 0.08152986],
       [0.99132153, 0.21343236, 0.12470677, 0.19283782],
       [0.67332681, 0.5671647 , 0.13419959, 0.0134772 ]])

In [15]:
arr = np.reshape(arr, (6,2))

In [16]:
arr

array([[0.65407132, 0.34268835],
       [0.18080346, 0.08152986],
       [0.99132153, 0.21343236],
       [0.12470677, 0.19283782],
       [0.67332681, 0.5671647 ],
       [0.13419959, 0.0134772 ]])

In [17]:
arr.flatten()

array([0.65407132, 0.34268835, 0.18080346, 0.08152986, 0.99132153,
       0.21343236, 0.12470677, 0.19283782, 0.67332681, 0.5671647 ,
       0.13419959, 0.0134772 ])